spring:
  application:
    name: savings-goal-api

  datasource:
    url: jdbc:mysql://localhost:3306/savings_goal?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080
